[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
async-trait = "0.1.52"
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["macros"] }
